#the goal of the repository object is to define where the helm chart of airflow is
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: apache-airflow
  namespace: flux-system
spec:
  interval: 1m
  url: https://airflow.apache.org/