#Helm Release Object to be deployed : release is an intance of a chart in k8s cluster
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  #name of the helm release fordeployment tool flux, argocd
  name: airflow
  namespace: dev
spec:
  interval: 30s
  #name of the release for helm
  releaseName: airflow-dev
  chart:
    spec:
      chart: airflow
      version: "1.9.0"
      sourceRef:
        kind: HelmRepository
        name: apache-airflow
        namespace: flux-system
  #chart values https://github.com/apache/airflow/blob/main/chart/values.yaml
  values:
    defaultAirflowTag: "2.8.1"
    airflowVersion: "2.8.1"
    fernetKey: "zTxhk7FuGqQVPZVoukLn5bGWOrgHzhQnBnaqAItcZGI="
    env:
      - name: "AIRFLOW__CORE__LOAD_EXAMPLES"
        value: "False"
      - name: "AIRFLOW__KUBERNETES_EXECUTOR__NAMESPACE"
        value: "dev"
      - name: "AIRFLOW__KUBERNETES_EXECUTOR__WORKER_CONTAINER_REPOSITORY"
        value: "apache/airflow"
      - name: "AIRFLOW__KUBERNETES_EXECUTOR__WORKER_CONTAINER_TAG"
        value: "slim-2.5.1-python3.8"
    executor: "KubernetesExecutor"
    createUserJob:
      useHelmHooks: false
    migrateDatabaseJob:
      useHelmHooks: false
    dags:
      persistence:
        enabled: False
      gitSync:
        enabled: True
        repo: https://github.com/Hilalem/airflow-dags.git
        branch: master
        maxFailures: 0
        subpath: ""
        wait: 60
    